.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
    echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST_PATH" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST_PATH:_authToken=$NPM_WRITE_TOKEN" >> ~/.npmrc
    echo "//$NPM_PROJECT_HOST_PATH_PREFIX$CI_PROJECT_ID$NPM_PROJECT_HOST_PATH_SUFFIX:_authToken=$NPM_WRITE_TOKEN" >> ~/.npmrc
    cat ~/.npmrc

stages:
  - build
  - publish

build:
  stage: build
  image: node:8-alpine
  script:
    - npm run build

publish:
  stage: publish
  image: node:8-alpine
  script:
    - *authenticate-to-npmjs
    - npm install
    - npm run make-distribution
    - cd lib/main
    - npm publish --access public
  only:
    - /^([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}(-(pre|rc)\.[0-9]{1,})?)$/
